Add missing error check in test code
Found by golangci-lint:
```
$ golangci-lint run
server/server_test.go:389:16: Error return value of `os.WriteFile` is not checked (errcheck)
			os.WriteFile(golden, body, 0644)
			            ^
```